apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: m85ciqdhn-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: m85ciqdhn-python 
  name: m85ciqdhn-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: m85ciqdhn-python 
